# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Marvin Lavechin'
mail:             'marvin.lavechin@gmail.com'
tagline:          'PhD Student'
team:             '<a href="http://www.lscp.net/persons/dupoux/bootphon/index.html">Cognitive Machine Learning</a> team'
lab:              '<a href="https://lscp.dec.ens.fr/en">Cognitive Sciences & Psycholinguistic Laboratory</a>'
description:      'PhD Student and open-science lover'
url:              https://github.com/MarvinLvn/homepage/
baseurl:          /

author:
  name:           'Marvin Lavechin'
  url:            https://github.com/MarvinLvn/homepage

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/MarvinLvn

gscholar:         https://scholar.google.com/citations?hl=fr&user=QvKvn9sAAAAJ

picture:
  path1:          images/picture.png